#!/bin/sh

# "conserve", a script to query and set Battery Conservation Mode on supported
# Lenovo laptops.

# Set your "battery conservation mode" file here:
target=/sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode

# Determine new mode
case $1 in
	-h | --help )
		cat <<-EOF
		Usage:
		  conserve [action]
		Interact with battery conservation mode on Lenovo laptops.

		Actions:
		  Query:    ?,             st(at(us)), q(uery)   DEFAULT
		  Enable:   1, on,  true,  n(o),       en(able)
		  Disable:  0, off, false, y(es),      dis(able)
		  Toggle:  -1,             t(og(gle)), sw(itch)
		EOF
		exit 0
		;;
	1 | on | enable | en | yes | y | true )
		mode=1 ;;
	0 | off | disable | dis | no | n | false )
		mode=0 ;;
	-1 | toggle | tog | t | switch | sw )
		mode=$((! `cat $target`)) ;;
	? | status | stat | st | query | q  | * )
		cat $target
		exit 0 ;;
esac

# Apply changes
echo $mode
echo $mode > $target
