#!/bin/sh
# Neovim needs a terminal to display itself, and thus can't be started directly
# by, for example, a keybind in i3. This script simply launches a terminal to
# contain a Neovim instance.

# NOTE: We assume Kitty as a reasonable default terminal emulator. To override
# this, set $TERMINAL in your environment, e.g. for Hyprland:
# $terminal = ghostty
# env = TERMINAL,$terminal

exec "${TERMINAL:-kitty}" -e nvim "$@"
